# Generated by Django 4.0.2 on 2022-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('joke', models.TextField()),
                ('answer', models.TextField()),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'unique_together': {('joke', 'answer')},
            },
        ),
    ]
